strategy:
  matrix:
    linux:
      imageName: 'ubuntu-18.04'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

steps:

  - script: |
      cmake . -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON && cmake --build .
    displayName: 'Build'

  - script: |
      ctest -VV .
    displayName: 'Test'

  - script: |
      cmake --build . --target funktions_examples_run
    displayName: 'Examples'
